# User-related actions
# user=site.greentable.controller.UserController

# Product-related actions
product=site.greentable.controller.ProductController

# Admin-related actions
admin=site.greentable.controller.AdminController

# Cart-related actions
# cart=site.greentable.controller.CartController

# Order-related actions
# order=site.greentable.controller.OrderController

# Review-related actions
# review=site.greentable.controller.ReviewController

# Event-related actions
# event=site.greentable.controller.EventController

# Farm-related actions
farm=site.greentable.controller.FarmController