# User-related actions
# user=site.greentable.controller.UserController

# Product-related actions
product=site.greentable.controller.ProductController

# Admin-related actions
admin=site.greentable.controller.AdminController

# Farm-related actions
farm=site.greentable.controller.FarmController