user=site.greentable.controller.UserControllerImpl
mypage=site.greentable.controller.MypageControllerImpl


# Admin-related actions
admin=site.greentable.controller.AdminController

# 중복 정의 제거하고 정확한 클래스 경로 지정
farm=site.greentable.controller.FarmController
product=site.greentable.controller.ProductController


# Cart-related actions
cart=site.greentable.controller.CartController

# Order-related actions
order=site.greentable.controller.OrderController

# Review-related actions
# review=site.greentable.controller.ReviewController

# Event-related actions
# event=site.greentable.controller.EventController


